app_homepage:
    path:     /{_locale}
    defaults: { _controller: AppBundle:Default:index, _locale: en }
    requirements:
        _locale: en|ru|ua

app:
    resource: @AppBundle/Controller/
    type:     annotation
    prefix:   /{_locale}
    defaults: { _locale: en }
    requirements:
        _locale: en|ru|ua
